version: '3'

services:
  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run start
    ports:
      - '3001:3001'
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    container_name: realworld-docker-db
    volumes:
      - mongodb_api:/data/db

  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    ports:
      - '3002:3002'
    restart: unless-stopped
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db

  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    command: npm run preview
    # ports:
    #   - '4173:4173'
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongodb_api:
  mongodb_auth:
