version: '3'

services:
  api:
    build: ./api
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    command: npm run dev
    # ports:
    #   - '5173:5173'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
