version: '3'

services:
  api:
    build: ./api
    container_name: realworld-docker-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - realworld-docker-network

  api_db:
    image: mongo:latest
    container_name: realworld-docker-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - realworld-docker-network

  auth:
    build: ./auth
    container_name: realworld-docker-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - realworld-docker-network

  users:
    build: ./users
    container_name: realworld-docker-users
    command: npm start
    restart: unless-stopped
    networks:
      - realworld-docker-network

  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - realworld-docker-network

  frontend:
    build: ./frontend
    container_name: realworld-docker-frontend
    command: npm run preview
    restart: unless-stopped
    networks:
      - realworld-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - realworld-docker-network

  mysql:
    image: mysql:latest
    container_name: realworld-docker-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - realworld-docker-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: realworld-docker-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '8080:80'
    networks:
      - realworld-docker-network
    depends_on:
      - mysql

volumes:
  mongodb_api:
  mongodb_auth:
  mysql_db:

networks:
  realworld-docker-network:
    driver: bridge
